// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHiZRx45N4OhRGLK27fdnqPtfmug8g500',
    appId: '1:263114028567:web:63dba99381195fa387ce52',
    messagingSenderId: '263114028567',
    projectId: 'solenstay-74f8e',
    authDomain: 'solenstay-74f8e.firebaseapp.com',
    storageBucket: 'solenstay-74f8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6FXHjvCr20xrSNLJWwNmr8OKCAhZDMA',
    appId: '1:263114028567:android:fd951974235daf6487ce52',
    messagingSenderId: '263114028567',
    projectId: 'solenstay-74f8e',
    storageBucket: 'solenstay-74f8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJ0qefc7uX2KQZqaLrIn_Yq_jF8zVv-o',
    appId: '1:263114028567:ios:d991aa5a71655c7e87ce52',
    messagingSenderId: '263114028567',
    projectId: 'solenstay-74f8e',
    storageBucket: 'solenstay-74f8e.firebasestorage.app',
    iosBundleId: 'com.solenstay.app',
  );
}
